"""Initial schema: sessions, files, chunks, messages.

Mirrors the shape version 2's `Base.metadata.create_all()` produced —
hand-written rather than autogenerated, so the history is explicit about
what version 2 already had versus what v3 adds. `chunks.embedding` is
deliberately NOT here; see 0002_pgvector, which adds the extension, the
column and its index as a separate, clearly-labelled step.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-11
"""
import sqlalchemy as sa
from alembic import op

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("owner_id", sa.String(128), nullable=True),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("files_total", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("files_done", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_sessions_owner_id", "sessions", ["owner_id"])

    op.create_table(
        "files",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("session_id", sa.String(36),
                 sa.ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False),
        sa.Column("filename", sa.String(400), nullable=False),
        sa.Column("kind", sa.String(20), nullable=False),
        sa.Column("raw_key", sa.String(600), nullable=False),
        sa.Column("text_key", sa.String(600), nullable=True),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_files_session_id", "files", ["session_id"])

    op.create_table(
        "chunks",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("session_id", sa.String(36),
                 sa.ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False),
        sa.Column("file_id", sa.String(36),
                 sa.ForeignKey("files.id", ondelete="CASCADE"), nullable=False),
        sa.Column("chunk_key", sa.String(80), nullable=False),
        sa.Column("source", sa.String(400), nullable=False),
        sa.Column("section", sa.String(400), nullable=True),
        sa.Column("kind", sa.String(20), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_chunks_session", "chunks", ["session_id"])
    op.create_index("ix_chunks_file", "chunks", ["file_id"])
    op.create_unique_constraint("uq_chunks_session_key", "chunks", ["session_id", "chunk_key"])

    op.create_table(
        "messages",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("session_id", sa.String(36),
                 sa.ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False),
        sa.Column("role", sa.String(20), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("sources", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_messages_session_id", "messages", ["session_id"])


def downgrade() -> None:
    op.drop_table("messages")
    op.drop_table("chunks")
    op.drop_table("files")
    op.drop_table("sessions")
